# version: "3.8"
services:
  mindflowy-notes-api:
    build:
      context: ./
      target: production
    restart: always
    container_name: mindflowy-notes-api
    depends_on:
      - mindflowy-notes-db
    ports:
      - 3000:3000
    env_file:
      - .env
    entrypoint: ./docker_entrypoint.sh

  mindflowy-notes-db:
    image: mariadb:lts-jammy
    restart: always
    expose:
      - 3306
    container_name: mindflowy-notes-db
    env_file:
      - .env
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      # MARIADB_RANDOM_ROOT_PASSWORD: yes
      MARIADB_USER: ${DB_USER}
    volumes:
      - mariadb_volume:/var/lib/mysql

volumes:
  mariadb_volume:
