version: "3.8"
services:
  mindstack-notes-api:
    build:
      context: ./
      target: dependencies
    restart: always
    container_name: mindstack-notes-api
    depends_on:
      - mindstack-notes-db
    ports:
      - 3000:3000
      # following is for DEVELOPMENT/debugging
      - 9229:9229
    env_file:
      - .env
    volumes:
      - ./:/home/node/app
    entrypoint: ./docker_entrypoint.development.sh

  mindstack-notes-db:
    image: mariadb:lts-jammy
    restart: always
    expose:
      - 27017
    container_name: mindstack-notes-db
    env_file:
      - .env
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      # MARIADB_RANDOM_ROOT_PASSWORD: yes
      MARIADB_USER: ${DB_USER}
    volumes:
      - mariadb_volume:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mariadb_volume:
